apiVersion: v1
kind: Namespace
metadata:
  name: backend-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: nikhildocker4424/eshop-backend:1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend-namespace
spec:
  selector:
    app: backend
  ports:
    - port: 5002
      protocol: TCP
      targetPort: 5000
  type: ClusterIP