kind: Namespace
apiVersion: v1
metadata:
  name: backend-namespace
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: backend-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: nikhildocker/eshop-backend:1
          ports:
            - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
    - port: 5002
      targetPort: 5000
  type: ClusterIP