apiVersion: v1
kind: Namespace
metadata:
  name: backend-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: nikhildocker4424/eshop-backend:1
          ports:
            - containerPort: 5000
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: AZURE_SQL_CATALOG_CONNECTION_STRING_KEY
              value: "CatalogConnection"
            - name: AZURE_SQL_IDENTITY_CONNECTION_STRING_KEY
              value: "IdentityConnection"
            - name: CatalogConnection
              value: "Server=db-service.backend-namespace.svc.cluster.local,1433;Database=Microsoft.eShopOnWeb.CatalogDb;User Id=sa;Password=secure-Random-P@ss-11234;TrustServerCertificate=true;"
            - name: IdentityConnection
              value: "Server=db-service.backend-namespace.svc.cluster.local,1433;Database=Microsoft.eShopOnWeb.Identity;User Id=sa;Password=secure-Random-P@ss-11234;TrustServerCertificate=true;"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend-namespace
spec:
  selector:
    app: backend
  ports:
    - port: 5002
      protocol: TCP
      targetPort: 5000
  type: ClusterIP