apiVersion: v1
kind: Namespace
metadata:
  name: db-namespace
---
apiVersion: apps/v1
kind: Deployment                                                                                                                                                                                                            
metadata:
  name: db-deployment
  namespace: db-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db-container
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          volumeMounts:
            - mountPath: mnt/database  
              name: db-storage
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "secure-Random-P@ss-11234"
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: backend-namespace
spec:
  selector:
    app: db
  ports:
    - port: 1433
      protocol: TCP
      targetPort: 1433
  type: ClusterIP

