kind: Namespace
apiVersion: v1
metadata:
  name: frontend-namespace
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deployment
  namespcae: frontend-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: nikhildocker/frontend:1
          ports:
            - containerPort: 80
          env: 
          - name: BACKEND_URL
            value: "http://backend-service:5002"
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
    - port: 81
      targetPort: 80
  type: LoadBalancer