apiVersion: v1
kind: Namespace
metadata:
  name: frontend-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespcae: frontend-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: nikhildocker/eshop-frontend:1
          ports:
            - containerPort: 80
          env: 
          - name: BACKEND_URL
            value: "http://backend-service.backend-namespace.svc.cluster.local:5002"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 81
      targetPort: 80
  type: NodePort