apiVersion: v1
kind: Namespace
metadata:
  name: frontend-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: nikhildocker4424/eshop-frontend:1
          ports:
            - containerPort: 80
          env: 
            - name: baseUrls__apiBase
              value: "http://backend-service.backend-namespace.svc.cluster.local:5002/api/"
            - name: baseUrls__webBase
              value: "http://frontend-service.frontend-namespace.svc.cluster.local:81/api"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend-namespace
spec:
  selector:
    app: frontend
  ports:
    - port: 81
      targetPort: 80
  type: NodePort