apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: db-pv-class
  persistantVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nfs:
    server: nfs-service.nfs-namespace.svc.cluster.local
    path: /mnt/nfs-share
