apiVersion: v1
kind: Namespace
metadata:
  name: nfs-namespace
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: nfs-namespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: pv-class
  resources: 
    requests:
      storage: 5Gi  