apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: db-namespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: db-pv-class
  resources: 
    requests:
      storage: 5Gi  