apiVersion: v1
kind: Namespace
metadata:
  name: db-namespace
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db
  namespace: db-namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-aws
  resources: 
    requests:
      storage: 5Gi  