apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-aws
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fstype: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
